import type { en } from "./en";

export const tr: typeof en = {
	"login.encrypted": "Uçtan uca şifreli mesajlaşma",
	"login.tab.login": "Giriş",
	"login.tab.register": "Kayıt ol",
	"login.placeholder.name": "Adınız",
	"login.placeholder.email": "E-posta",
	"login.placeholder.password": "Parola",
	"login.placeholder.confirmPassword": "Parolayı tekrar girin",
	"login.error.passwordMismatch": "Parolalar eşleşmiyor",
	"login.error.nameRequired": "İsim gerekli",
	"login.button.creating": "Hesap oluşturuluyor...",
	"login.button.loggingIn": "Giriş yapılıyor...",
	"login.button.create": "Hesap Oluştur",
	"login.button.login": "Giriş yap",
	"login.footer": "Mesajlarınız uçtan uca şifrelidir",

	"ios.title": "Lütfen Safari kullanın",
	"ios.description": "iOS'ta Apelsin en iyi Safari'de çalışır. Push bildirimleri, çevrimdışı destek ve tam uygulama deneyimi için bu sayfayı Safari'de açın.",
	"ios.copyLink": "Bağlantıyı kopyala",

	"chatList.addContact": "Kişi ekle",
	"chatList.profile": "Profil",
	"chatList.search": "Ara veya yeni sohbet başlat",
	"chatList.enableNotifications": "Bildirimleri aç",
	"chatList.enableNotificationsDesc": "Mesaj aldığınızda bildirim alın",
	"chatList.pendingRequest": "Bağlantı isteği",
	"chatList.pendingRequests": "Bağlantı istekleri",
	"chatList.pendingTap": "Görüntülemek ve yanıtlamak için dokunun",
	"chatList.noContacts": "Henüz kişi yok",
	"chatList.addAContact": "Kişi ekle",
	"chatList.you": "Siz: ",
	"chatList.voiceMessage": "Sesli mesaj",
	"chatList.photo": "Fotoğraf",

	"chat.emptyState": "Mesajlar uçtan uca şifrelidir. Başlamak için bir mesaj gönderin.",
	"chat.today": "Bugün",
	"chat.yesterday": "Dün",
	"chat.unreadMessage": "okunmamış mesaj",
	"chat.unreadMessages": "okunmamış mesaj",
	"chat.replyPhoto": "Fotoğraf",
	"chat.replyVoice": "Sesli mesaj",
	"chat.replyYou": "Siz",
	"chat.inputPlaceholder": "Bir mesaj yazın",
	"chat.recording": "Kaydediliyor...",
	"chat.reply": "Yanıtla",

	"presence.typing": "yazıyor...",
	"presence.recording": "ses kaydediyor...",
	"presence.online": "çevrimiçi",
	"presence.lastSeen": "son görülme {time}",
	"presence.establishing": "Şifreleme kuruluyor...",
	"presence.encrypted": "Uçtan uca şifreli",
	"presence.offline": "Çevrimdışı - {count} önbellekte",

	"profile.title": "Profil",
	"profile.displayName": "Görünen ad",
	"profile.namePlaceholder": "Adınız",
	"profile.email": "E-posta",
	"profile.save": "Değişiklikleri Kaydet",
	"profile.saving": "Kaydediliyor...",
	"profile.linkDevice": "Başka Bir Cihaz Bağla",
	"profile.activeDevices": "Etkin Cihazlar",
	"profile.thisDevice": "(bu cihaz)",
	"profile.lastActive": "Son etkinlik {date}",
	"profile.revoke": "Kaldır",
	"profile.uploading": "Yükleniyor...",
	"profile.logout": "Çıkış yap",

	"addContact.title": "Kişi Ekle",
	"addContact.description": "Bağlanmak istediğiniz kişinin e-posta adresini girin. Sohbet edebilmeniz için isteğinizi kabul etmesi gerekir.",
	"addContact.placeholder": "arkadas@ornek.com",
	"addContact.sending": "Gönderiliyor...",
	"addContact.send": "İstek Gönder",

	"pending.title": "Bağlantı İstekleri",
	"pending.empty": "Bekleyen istek yok",
	"pending.accept": "Kabul et",
	"pending.decline": "Reddet",

	"deviceLink.title": "Bu Cihazı Bağla",
	"deviceLink.cancel": "İptal",
	"deviceLink.generating": "QR kodu oluşturuluyor...",
	"deviceLink.scanTitle": "Ana cihazınızdan tarayın",
	"deviceLink.scanDesc": "Diğer cihazınızda Apelsin'i açın, Profil'e gidin ve bu kodu taramak için \"Cihaz Bağla\"ya dokunun.",
	"deviceLink.waiting": "Tarama bekleniyor...",
	"deviceLink.receiving": "Şifreleme anahtarları alınıyor...",
	"deviceLink.expired": "Eşleştirme oturumu sona erdi. Lütfen tekrar deneyin.",
	"deviceLink.tryAgain": "Tekrar Dene",

	"qrScanner.title": "Cihaz Bağla",
	"qrScanner.instruction": "Kameranızı diğer cihazda gösterilen QR koduna doğrultun",
	"qrScanner.transferring": "Şifreleme anahtarları aktarılıyor...",
	"qrScanner.success": "Cihaz başarıyla bağlandı!",
	"qrScanner.goBack": "Geri Dön",
	"qrScanner.cameraError": "Kamera erişimi reddedildi",
	"qrScanner.browserError": "Bu tarayıcıda QR tarama desteklenmiyor. Chrome, Edge veya Safari 17+ kullanın.",

	"call.calling": "Aranıyor...",
	"call.incoming": "Gelen arama...",
	"call.connecting": "Bağlanıyor...",
	"call.ended": "Arama sona erdi",

	"error.failedToSendRequest": "İstek gönderilemedi",

	"language.title": "Dil",
};
